version: '3.3'
services:
  mongo_db:
    image: ${TAG_MONGO}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    build: ./ui
    image: ${USERNAME}/${TAG_UI}
    ports:
      - ${UI_PORTS}
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${USERNAME}/${TAG_POST}
    networks:
      - front_net
      - back_net
  comment:
    build: ./comment
    image: ${USERNAME}/${TAG_COMMENT}
    networks:
      - front_net
      - back_net
volumes:
  post_db:
networks:
  front_net:
  back_net:
